version: '3.9'

services:
    github-notifier:
        restart: unless-stopped
        build: .
        container_name: github-notifier
        command:
                - /bin/bash
                - -c
                - |
                  cd /mnt_src
                  node -e 'require("./github_notifier/rest")'
                  
        # volumes:
        #     - ./enabler:/mnt_src
        #     # - /usr/bin/docker:/usr/bin/docker # making docker client accessible inside docker: mount /usr/bin/docker and /var/run/docker.sock
        #     # - /var/run/docker.sock:/var/run/docker.sock

        # environment:
        #     - PRODUCTION_MODE=1
