version: "3.9"

services:
    github-notifier:
        restart: unless-stopped
        build: .
        container_name: github-notifier
        command:
            - /bin/bash
            - -c
            - |
                node -e 'require("./github_notifier/rest")'

        # environment:
        #     - PRODUCTION_MODE=1
